### PR TITLE
Use annotation to ensure correct Swagger generation for `expiryDate`

### PR DESCRIPTION
**Pull request by CaseyODonnell92**
I haven't made this change reflect in the versioning as it only impacts the generation of the Swagger document for this interface as well as the resulting web documentation.

If this should accompany a version bump, I will make the necessary changes to the release notes and POM.

### CODE REVIEW

**Review by phillipvanheerden — APPROVED** [review]
Thanks for the explanation :-)

**Review by TimElectrum — CHANGES_REQUESTED** [review]
I think we should bump the version and add to the release notes too

**Comment by phillipvanheerden** [comment]
Ah yes, thanks @TimElectrum. Sorry @CaseyODonnell92 I did miss that, my bad.

**Comment by CaseyODonnell92** [comment]
Cool, thanks @TimElectrum. I'm assuming that is a patch version.

**Comment by TimElectrum** [comment]
> Cool, thanks @TimElectrum. I'm assuming that is a patch version.

yeah, I think so.

I'm kinda surprised that if we use the standard Java date-time type, there isn't a way to de.serialise from/to a common format like ISO-8601. Have you had a look around the internet regarding this?

Happy with this approach though if there's no other commonly accepted way

**Comment by CaseyODonnell92** [comment]
I can have another look. If you look at this issue, it seems like you can specify a format in that annotation now (we just aren't using that version). Let me see if using a version of the Swagger libraries with support for the `format` annotation property would allow us to specify `dataType=String, format=date-time`.

**Comment by CaseyODonnell92** [comment]
The issue is not actually with serialisation (we use object mappers that cater for both Joda and Java date/time types). This issue is just to do with Swagger integration. 
I've realised that we can directly use the [OpenAPI supported `dateTime` type](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#data-types) as a more sensible override. I think this is better.

**Review by TimElectrum — APPROVED** [review]
I presume you've actually checked the resulting swagger

**Comment by CaseyODonnell92** [comment]
> I presume you've actually checked the resulting swagger

I sure have!

**Pull request merged**
